spring:
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 692886957287-663ep6r6ds8ee0oukr9f5mrqof57k6bj.apps.googleusercontent.com
            client-secret: pVQcqYjwp_7fYyYdOJfkd5rk
            scope: profile,email
          facebook:
            client-id: 564162601158748
            client-secret: dd56c82cf93b958f1d00e30b355df0c2
            user-info-uri: https://graph/facebook/com/me?fields=id,name,email,picture
            scope: email
          naver:
            client-id: qJONuabRwLzw44TBZavZ
            client-secret: 2fGz3R2u8B
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          kakao:
            client-id: 9157b7a28ea73a1fe1a6ab9d0ea8520e
            client-secret: 1PmERaoLIQ2tk5pEB3divxtkNmY4ONWe
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: profile,account_email
            client-name: kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
